# Generated by Django 5.2.17 on 2026-09-15 18:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(blank=True, max_length=30, unique=True, verbose_name='N° de commande')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('paid', 'Payée'), ('shipped', 'Expédiée'), ('delivered', 'Livrée'), ('cancelled', 'Annulée')], default='pending', max_length=12, verbose_name='Statut')),
                ('payment_method', models.CharField(choices=[('online', 'Paiement en ligne (CIB / Edahabia)'), ('cod', 'Paiement à la livraison')], default='online', max_length=10, verbose_name='Mode de paiement')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('first_name', models.CharField(max_length=120, verbose_name='Prénom')),
                ('last_name', models.CharField(max_length=120, verbose_name='Nom')),
                ('phone', models.CharField(max_length=20, verbose_name='Téléphone')),
                ('address', models.CharField(max_length=255, verbose_name='Adresse')),
                ('city', models.CharField(max_length=120, verbose_name='Ville / Commune')),
                ('wilaya', models.CharField(max_length=80, verbose_name='Wilaya')),
                ('postal_code', models.CharField(blank=True, max_length=20, verbose_name='Code postal')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Sous-total (DA)')),
                ('shipping', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Frais de port (DA)')),
                ('total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total (DA)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créée le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Mise à jour le')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Client')),
            ],
            options={
                'verbose_name': 'Commande',
                'verbose_name_plural': 'Commandes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200, verbose_name='Nom du produit')),
                ('sku', models.CharField(blank=True, max_length=60, verbose_name='Référence')),
                ('variant_label', models.CharField(blank=True, max_length=120, verbose_name='Déclinaison')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix unitaire (DA)')),
                ('quantity', models.PositiveIntegerField(verbose_name='Quantité')),
                ('line_total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total ligne (DA)')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order', verbose_name='Commande')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='catalog.product', verbose_name='Produit')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.productvariant', verbose_name='Déclinaison')),
            ],
            options={
                'verbose_name': 'Ligne de commande',
                'verbose_name_plural': 'Lignes de commande',
            },
        ),
    ]
