# Generated by Django 5.2.17 on 2026-09-15 18:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_id', models.CharField(blank=True, max_length=100, unique=True, verbose_name='Chargily checkout ID')),
                ('checkout_url', models.URLField(blank=True, verbose_name='Lien de paiement')),
                ('amount', models.IntegerField(verbose_name='Montant (DA)')),
                ('payment_method', models.CharField(blank=True, default='edahabia', max_length=10, verbose_name='Mode de paiement')),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('PAID', 'Payé'), ('FAILED', 'Échoué'), ('CANCELED', 'Annulé'), ('EXPIRED', 'Expiré')], default='PENDING', max_length=10, verbose_name='Statut')),
                ('extra_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='orders.order', verbose_name='Commande')),
            ],
            options={
                'verbose_name': 'Paiement',
                'verbose_name_plural': 'Paiements',
                'ordering': ['-created_at'],
            },
        ),
    ]
