# Generated by Django 5.2.17 on 2026-09-15 18:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Nom')),
                ('slug', models.SlugField(blank=True, max_length=140, unique=True, verbose_name='Slug')),
                ('image', models.ImageField(blank=True, null=True, upload_to='categories/', verbose_name='Image')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='catalog.category', verbose_name='Catégorie parente')),
            ],
            options={
                'verbose_name': 'Catégorie',
                'verbose_name_plural': 'Catégories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom du produit')),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True, verbose_name='Slug')),
                ('sku', models.CharField(blank=True, max_length=60, verbose_name='Référence (SKU)')),
                ('short_description', models.CharField(blank=True, help_text='Phrase courte affichée dans les listes de produits.', max_length=255, verbose_name='Accroche')),
                ('description', models.TextField(blank=True, help_text='Description riche affichée sur la page produit.', verbose_name='Description détaillée')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix de vente (DA)')),
                ('compare_at_price', models.DecimalField(blank=True, decimal_places=2, help_text='Ancien prix affiché en promo (optionnel).', max_digits=10, null=True, verbose_name='Prix barré (DA)')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='Stock')),
                ('is_active', models.BooleanField(default=True, verbose_name='En ligne')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Mis en avant')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Mis à jour le')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.category', verbose_name='Catégorie')),
            ],
            options={
                'verbose_name': 'Produit',
                'verbose_name_plural': 'Produits',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=120, verbose_name='Intitulé')),
                ('value', models.CharField(max_length=255, verbose_name='Valeur')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='catalog.product', verbose_name='Produit')),
            ],
            options={
                'verbose_name': 'Caractéristique',
                'verbose_name_plural': 'Caractéristiques',
                'ordering': ['order', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/', verbose_name='Image')),
                ('alt', models.CharField(blank=True, help_text="Description de l'image pour le référencement.", max_length=255, verbose_name='Texte alternatif')),
                ('is_primary', models.BooleanField(default=False, help_text='Affichée en premier sur la fiche produit.', verbose_name='Image principale')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalog.product', verbose_name='Produit')),
            ],
            options={
                'verbose_name': 'Image produit',
                'verbose_name_plural': 'Images produit',
                'ordering': ['order', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ex. Taille M / Noir', max_length=120, verbose_name='Déclinaison')),
                ('sku', models.CharField(blank=True, max_length=60, verbose_name='Référence (SKU)')),
                ('extra_price', models.DecimalField(decimal_places=2, default=0, help_text="S'ajoute au prix du produit.", max_digits=10, verbose_name='Supplément de prix (DA)')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='Stock')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='catalog.product', verbose_name='Produit')),
            ],
            options={
                'verbose_name': 'Déclinaison',
                'verbose_name_plural': 'Déclinaisons',
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Nom')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail')),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], verbose_name='Note')),
                ('comment', models.TextField(verbose_name='Avis')),
                ('is_approved', models.BooleanField(default=False, help_text='Les avis approuvés sont affichés sur la fiche produit.', verbose_name='Approuvé')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='catalog.product', verbose_name='Produit')),
            ],
            options={
                'verbose_name': 'Avis client',
                'verbose_name_plural': 'Avis clients',
                'ordering': ['-created_at'],
            },
        ),
    ]
